django_xlstore/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from xlstore import views
from xlstore.company import CompanyRegister
from xlstore.user import UserRegister
from xlstore.post import PostController
from xlstore.post_reply import PostReplyController
from xlstore.product import ProductController
from xlstore.product_comment import ProductCommentController
from xlstore.category import ProductCategoryController
from xlstore.trade import TradeController
from xlstore.user import UserController
from xlstore.company import CompanyController
from xlstore.advertisment import AdvertismentController
import urllib


post = PostController()
reply = PostReplyController()
product = ProductController()
comment = ProductCommentController()
category = ProductCategoryController()
trade = TradeController()
user = UserController()
company = CompanyController()
advert = AdvertismentController()


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^managment/', include('xlstore_managment.urls')),
    url(r'^ecommerce/', include('xlstore_ecommerce.urls')),
    #url(r'^api/', include('xlstoreapi.urls')),
    url(r'^home/$', product.get_home_page, name='home'),
    url(r'^$', product.get_home_page, name='home_simple'),
    url(r'^products/$', product.get_products_page, name='products'),
    url(r'^posts/$', post.get_posts_page, name='posts'),
    url(r'^advertisments/$', advert.get_advertisments_page, name='advertisments'),
    url(r'^search/$', views.search_products_comp_users, name='search'),
    url(r'^address/add/new/$', user.add_address, name='add_address'),
    url(r'^load/map/(?P<source>[^/]+)/(?P<any_id>\d+)/load/', views.load_geo_map, name='load_geo_map'),
    
    #User Login, Register, Auth and logout

    url(r'^user/signup/$', UserRegister.as_view(), name='regist_user'),
    url(r'^user/login/$', user.get_user_login_page, name='login_user'),
    url(r'^user/logout/$', user.get_user_logout_page, name='logout_user'),
    url(r'^user/invalid/$', user.get_user_invalid_page, name='invalid_user'),
    url(r'^user/auth/$', user.get_user_auth_page, name='auth_user'),
    url(r'^user/company/categories/$', user.load_company_categories_users, name='user_company_categories'),
    url(r'^user/company/categories/(?P<category>\d+)/$', user.load_company_category_users, name='user_company_category'),
    url(r'^user/company/bills_carts/$', user.get_user_bills_and_carts, name='user_company_bills_carts_all'),
    url(r'^user/company/bills_carts/(?P<company>\d+)/$', user.get_user_bills_and_carts_company, name='user_company_bills_carts_company'),

    #View User Profile and Other

    url(r'^user/(?P<user_name>[^/]+)/$', user.get_user_profile, name='user_profile'),
    url(r'^user/(?P<user_name>[^/]+)/posts/$', user.get_user_profile, name='user_posts'),
    url(r'^user/(?P<user_name>[^/]+)/following/$', user.get_user_following_page, name='user_following'),
    url(r'^user/(?P<user_name>[^/]+)/followers/$', user.get_user_followers_page, name='user_followers'),
    url(r'^user/(?P<user_name>[^/]+)/companies/$', user.get_user_companies_page, name='user_companies'),
    url(r'^user/(?P<user_name>[^/]+)/interess/$', user.get_user_interess_page, name='user_interess'),
    
    url(r'^user/update/user_cover_image/$', user.update_user_cover_image, name='user_cover_edit'),
 	url(r'^user/update/user_profile_image/$', user.update_user_profile_image, name='user_profile_image_edit'),
 	url(r'^user/update/user_profile/$', user.update_user_profile, name='user_profile_edit'),
 	
    url(r'^user/add/post/$', post.add_post, name='user_save_post'),
    url(r'^user/save/post/$', post.save_post, name='user_add_post'),
 	url(r'^user/posts/(?P<post_id>\d+)/$', post.get_single_post_ajax, name='single_post_ajax'),
 	url(r'^user/user/follow/$', user.user_follow_user, name='user_follow_user'),
 	
    url(r'^user/posts/(?P<post_id>\d+)/edit/$', post.get_edit_post, name='user_edit_post'),
 	url(r'^user/save/(?P<post_id>\d+)/edit/$', post.save_edit_post, name='user_edit_save_post'),
 	url(r'^user/posts/article/(?P<post_id>\d+)/delete/$', post.delete_post, name='user_delete_post'),
 	
    url(r'^user/products/like_dislike/$', product.user_like_dislike_product, name='user_like_dislike_product'),
 	url(r'^user/posts/like_dislike/$', post.user_like_dislike_post, name='user_like_dislike_post'),
 	
    url(r'^user/posts/reply/(?P<post_id>\d+)/$', reply.get_post_reply, name='user_post_reply'),
 	url(r'^user/save/reply/(?P<post_id>\d+)/$', reply.save_post_reply, name='user_save_post_reply'),
 	
    url(r'^user/posts/(?P<post_id>\d+)/replies/$', reply.load_post_replies, name='user_load_post_replies'),
 	url(r'^user/posts/replies/(?P<reply_id>\d+)/delete/$', reply.delete_post_reply, name='user_delete_post_reply'),
 	url(r'^user/posts/replies/(?P<reply_id>\d+)/edit/$', reply.edit_post_reply, name='user_edit_post_reply'),
 	url(r'^user/posts/replies/(?P<reply_id>\d+)/edit_page/$', reply.get_edit_post_reply, name='user_edit_page_reply'),

    #Company Login, Register, Auth and logout

    url(r'^company/signup/$', CompanyRegister.as_view(), name='regist_comp'),
    url(r'^company/login/$', company.get_comp_login_page, name='login_comp'),
    url(r'^company/logout/$', company.get_comp_logout_page, name='logout_comp'),
    url(r'^company/invalid/$', company.get_comp_invalid_page, name='invalid_comp'),
    url(r'^company/auth/$', company.get_comp_auth_page, name='auth_comp'),

    #View Company Profile

 	url(r'^company/(?P<company_name>[^/]+)/$', company.get_comp_profile, name='comp_profile'),
 	url(r'^company/(?P<company_name>[^/]+)/products/$', company.get_comp_profile, name='comp_profile_2'),
 	url(r'^company/(?P<company_name>[^/]+)/posts/$', company.get_comp_posts, name='comp_posts'),
 	url(r'^company/(?P<company_name>[^/]+)/profile/$', company.get_comp_about, name='comp_about'),
 	url(r'^company/(?P<company_name>[^/]+)/categories/$', company.get_comp_categories, name='comp_categories'),
 	url(r'^company/(?P<company_name>[^/]+)/followers/$', company.get_comp_followers, name='comp_followers'),
 	url(r'^company/(?P<company_name>[^/]+)/advertisments/$', company.get_comp_advertisments, name='comp_advertisments'),
 	
    url(r'^company/update/company_profile_image/$', company.update_comp_profile_image, name='comp_profile_image_edit'),
 	url(r'^company/update/company_cover_image/$', company.update_comp_cover_image, name='comp_cover_edit'),
 	url(r'^company/update/company_profile/$', company.update_company_profile, name='comp_profile_edit'),
    url(r'^company/add/category/$', category.get_category_template, name='comp_add_category'),
 	url(r'^company/save/category/$', category.save_category, name='comp_save_category'),
    url(r'^company/add/product/$', product.add_product, name='comp_add_product'),
 	url(r'^company/save/product/$', product.save_product, name='comp_save_product'),
 	
    url(r'^company/(?P<company_name>[^/]+)/products/(?P<product_id>\d+)/$', product.get_single_product, name='single_product'),
 	url(r'^company/products/(?P<product_id>\d+)/$', product.get_single_product_ajax, name='single_product_ajax'),
    url(r'^company/products/(?P<product_id>\d+)/advertisment/$', product.get_product_advertisment, name='get_product_advertisment'),
    
    url(r'^edit/products/(?P<product_id>\d+)/template/$', product.get_edit_product, name='get_edit_single_product'),
 	url(r'^edit/products/(?P<product_id>\d+)/$', product.edit_product, name='edit_single_product'),
    
    url(r'^upload/products/(?P<product_id>\d+)/template/$', product.get_upload_more_images, name='get_upload_product_images'),
 	url(r'^upload/products/(?P<product_id>\d+)/$', product.upload_more_images, name='upload_product_images'),

 	url(r'^company/(?P<company_name>[^/]+)/categories/(?P<category_id>\d+)/$', category.get_single_category, name='single_category'),
    url(r'^edit/categories/(?P<category_id>\d+)/$', category.edit_category, name='edit_single_category'),
 	url(r'^edit/categories/(?P<category_id>\d+)/template/$', category.get_edit_category_template, name='get_edit_single_category'),
    
    url(r'^save/advertisment/(?P<product_id>\d+)/template/$', product.get_advertise_product, name='get_advertise_product'),
 	url(r'^save/advertisment/(?P<product_id>\d+)/$', product.advertise_product, name='advertise_product'),
 	
    url(r'^company/user/follow/$', company.user_follow_company, name='user_follow_company'),
 	url(r'^company/user/interess/$', product.user_interess_product, name='user_interess_product'),
 	url(r'^company/product/add_comment/$', comment.product_add_comment, name='product_add_comment'),
 	url(r'^company/product/comments/(?P<product_id>\d+)/$', comment.product_load_comments_main, name='product_load_comment_main'),
 	url(r'^company/product/comments_else/item=(?P<product_id>\d+)/$', comment.product_load_comments_else, name='product_load_comment_else'),
 	url(r'^company/product/comments/(?P<comment_id>\d+)/edit_page/$', comment.get_edit_product_comment, name='product_comment_edit_page'),
 	url(r'^company/product/comments/(?P<comment_id>\d+)/edit/$', comment.edit_product_comment, name='product_comment_edit'),
 	url(r'^company/product/comments/(?P<comment_id>\d+)/delete/$', comment.delete_product_comment, name='product_comment_delete'),

 	#Product Trade

 	url(r'^company/product/trade/(?P<product_id>\d+)/start/$', trade.start_product_trade, name='start_product_trade'),
 	url(r'^user/trade/t/$', trade.get_user_trades, name='user_all_trades'),
 	url(r'^company/trade/t/$', trade.get_company_trades, name='company_all_trades'),
 	url(r'^user/trade/(?P<trade_id>\d+)/$', trade.get_user_single_trade, name='user_single_trade'),
 	url(r'^company/trade/(?P<trade_id>\d+)/$', trade.get_company_single_trade, name='company_single_trade'),
 	
    url(r'^trade/message/(?P<trade_id>\d+)/$', trade.load_trade_messages, name='trade_messages'),

xlstore_managment/forms.py
from datetime import datetime, timedelta
from django import forms
from models import MS_LicenceKey, MS_LicenceKeyActivations, MS_CompanyTeller
from xlstore.forms import CURRENCIES
from django.core.exceptions import ValidationError


STATUS = (
		('activated', 'Activated'),
		('desactivated', 'Desactivated'),
		('paused', 'Paused')
	)


today = datetime.now().date()
expary_date = datetime.now().date() + timedelta(days=30)


class MS_LicenceKeyForm(forms.ModelForm):
	licence_key = forms.CharField(widget=forms.TextInput(attrs={'style':'width:40%'}))
	status = forms.ChoiceField(widget=forms.Select(attrs={'style':'width:40%'}), choices=STATUS)
	expary_date = forms.DateField(widget=forms.DateInput(attrs={'style':'width:40%', 'class':'vDateField', 'value':expary_date}))
	ammount = forms.CharField(widget=forms.NumberInput(attrs={'min':'1', 'style':'width:40%'}))
	currency = forms.ChoiceField(widget=forms.Select(attrs={'style':'width:40%'}), choices=CURRENCIES)

	def __init__(self, *args, **kwargs):
		super(MS_LicenceKeyForm, self).__init__(*args, **kwargs)
		self.fields['company'].disabled = True
		self.fields['licence_key'].disabled = True
		self.fields['status'].required = False
		self.fields['activated_date'].disabled = True
		self.fields['activated_date'].value = datetime.now().date()
		self.fields['expary_date'].value = datetime.now().date() + timedelta(days=30)

	class Meta:
		fields = ('company', 'licence_key', 'status', 'ammount', 'currency', 'activated_date', 'expary_date',)
		model = MS_LicenceKey


class MS_TellerForm(forms.ModelForm):
	full_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Enter Teller Full Name'}))
	username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Enter Teller Username'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':'Enter Teller Email'}))
	address = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Enter Teller Address'}))
	phone_number = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Enter Teller Phone Number', 'type':'tel'}))
	teller_image = forms.ImageField(widget=forms.FileInput(attrs={'required':'required', 'accept':'images/*'}))

	class Meta:
		fields = ('teller_image','full_name', 'username', 'email', 'address', 'phone_number',)
		model = MS_CompanyTeller


class MS_AdminUpdateTeller(forms.ModelForm):
	full_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Enter Teller Full Name'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':'Enter Teller Email'}))
	address = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Enter Teller Address'}))
	phone_number = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Enter Teller Phone Number', 'type':'tel'}))

	class Meta:
		fields = ('full_name', 'email', 'address', 'phone_number',)
		model = MS_CompanyTeller

templates/managment/msteller/add_teller.html
<div class="xl-add-product" style="width:40%">
    <style type="text/css">
        .intl-tel-input{width: 100%;}
        input[type=tel]{width: 100% !important;}
        input[type=file]{
            position: absolute;
            margin-top: -35px;
            width: 40%;
            opacity: 0;
            cursor: pointer;
        }
    </style>
    {% if session_ms %}
        <h2>Add Teller</h2>
        <form id="add_new_teller_form" method="post" action="{% url 'managment_mstl_add' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <span id="add_teller_image" for="id_teller_image"><i class="icon ion-ios-camera"></i> Add Image</span>
            {{teller_form}}
            <div style="margin-top:8px;">
                <input type="checkbox" name="is_admin" /><span style="margin-left:8px;">Can be admin also</span>
            </div>
            <button type="submit" style="background:lightgreen;">Save</button>
            <button type="button" style="background:red;" id="close_add_teller">Cancel</button>
        </form>
    {% else %}
        <p class="xl-error">ONLY FOR COMPANIES MS</p>
    {% endif %}

    <script type="text/javascript">

        $("#close_add_teller").click(function(){
            $(".mfp-close").click();
        });

        var set_country_code = setInterval(function(){
            if($(".intl-tel-input .country-list").length > 0){
                $(".intl-tel-input .country-list li").each(function(){
                    if($(this).hasClass('active')){
                        var country_code = $(this).attr("data-dial-code");
                        $("#id_phone_number").val("+"+country_code);
                    }
                });
            }
        });

        setInterval(function(){
            if($("#id_phone_number").val() != ""){
                clearInterval(set_country_code);
            }else{
                setInterval(set_country_code);
            }
        });

        $(".intl-tel-input .country-list li").click(function(){
    		var country_code = $(this).attr("data-dial-code");
    		$("#id_phone_number").val("+" + country_code);
    	});

        $("#id_phone_number").intlTelInput({
    		initialCountry: "auto",
    		geoIpLookup: function(callback) {
    			$.get('http://ipinfo.io', function() {}, "jsonp").always(function(resp) {
    				var countryCode = (resp && resp.country) ? resp.country : "";
    				callback(countryCode);
    			});
    		},
        });

        $("#add_new_teller_form").submit(function(e){
            e.preventDefault();
            var formData = new FormData($(this)[0]);
            $.ajax({
                type:'POST',
                url:$(this).attr('action'),
                data:formData,
                processData: false,
                async: false,
                cache: false,
                contentType: false,
                success:function(success){
                    $(".mfp-close").click();
                    load_msp_products("{% url 'managment_mstl_all' %}");
                    $.alert({theme:'material',title:'Success',icon:'icon ion-checkmark-circled',content:success,type: 'green'});
                },
                error: function(error){
                    showErrorMessage("error", error);
                }
            });
        });
    </script>
</div>

templates/managment/msteller/admin_update_teller.html
<div class="xl-add-product" style="width:40%">
    <style type="text/css">
        .intl-tel-input{width: 100%;}
        input[type=tel]{width: 100% !important;}
        input[type=file]{
            position: absolute;
            margin-top: -35px;
            width: 40%;
            opacity: 0;
            cursor: pointer;
        }
    </style>
    {% if session_ms %}
        <h2>Update Teller</h2>
        <form id="add_new_teller_form" method="post" action="{% url 'admin_update_teller' teller.pk %}" enctype="multipart/form-data">
            {% csrf_token %}
            <!--<span id="add_teller_image" for="id_teller_image"><i class="icon ion-ios-camera"></i> Add Image</span>-->
            {{teller_form}}
            <button type="submit" style="background:lightgreen;">Save</button>
            <button type="button" style="background:red;" id="close_add_teller">Cancel</button>
        </form>
    {% else %}
        <p class="xl-error">ONLY FOR COMPANIES MS</p>
    {% endif %}

    <script type="text/javascript">

        $("#close_add_teller").click(function(){
            $(".mfp-close").click();
        });

        var set_country_code = setInterval(function(){
            if($(".intl-tel-input .country-list").length > 0){
                $(".intl-tel-input .country-list li").each(function(){
                    if($(this).hasClass('active')){
                        var country_code = $(this).attr("data-dial-code");
                        $("#id_phone_number").val("+"+country_code);
                    }
                });
            }
        });

        setInterval(function(){
            if($("#id_phone_number").val() != ""){
                clearInterval(set_country_code);
            }else{
                setInterval(set_country_code);
            }
        });

        $(".intl-tel-input .country-list li").click(function(){
    		var country_code = $(this).attr("data-dial-code");
    		$("#id_phone_number").val("+" + country_code);
    	});

        $("#id_phone_number").intlTelInput({
    		initialCountry: "auto",
    		geoIpLookup: function(callback) {
    			$.get('http://ipinfo.io', function() {}, "jsonp").always(function(resp) {
    				var countryCode = (resp && resp.country) ? resp.country : "";
    				callback(countryCode);
    			});
    		},
        });

        $("#id_teller_image").removeAttr("required");

        $("#add_new_teller_form").submit(function(e){
            e.preventDefault();
            var formData = new FormData($(this)[0]);
            $.ajax({
                type:'POST',
                url:$(this).attr('action'),
                data:formData,
                processData: false,
                async: false,
                cache: false,
                contentType: false,
                success:function(success){
                    $(".mfp-close").click();
                    loadMSProductts("{% url 'managment_mstl_single_teller' teller.pk %}");
                    if (success == "ok"){
                        $.alert({theme:'material',title:'Success',icon:'icon ion-checkmark-circled',content:'Teller Updated Successfully !!!',type: 'green'});
                    }else{
                        $.alert({theme:'material',title:'Error',icon:'icon ion-close-circled',content:success,type: 'red'});
                    }
                },
                error: function(error){
                    showErrorMessage("error", error);
                }
            });
        });
    </script>
</div>

templates/managment/msteller/teller.html
{% load staticfiles %}
{% load humanize %}
<div class="xl-ms-product">
    <div class="xl-ms-product-details">
        <h2>Teller Information</h2>
        <div class="product_image">
            <img src="{{teller.teller_image.url}}" />
        </div>
        <h4 style="margin-bottom:10px;"><strong>{{teller.full_name}}</strong></h4>
        <p><strong>Email : </strong>{{teller.email}}</p>
        <p><strong>Address : </strong>{{teller.address}}</p>
        <p><strong>Phone Number : </strong>{{teller.phone_number}}</p>
        <p><strong>Is Admin : </strong>{{teller.is_admin}}</p>
        <button type="button" style="background:#00c6d7;" id="open_edit_ms_teller" href="{% url 'admin_update_teller_temp' teller.pk %}">Edit Teller</button>
        {% if teller.is_admin == True %}
            <button type="button" style="background:#999;" id="change_teller_is_admin" data-about="unmake" data-url="{% url 'admin_update_teller_admin' teller.pk %}">Unmake admin</button>
        {% else %}
            <button type="button" style="background:#999;" id="change_teller_is_admin" data-about="make" data-url="{% url 'admin_update_teller_admin' teller.pk %}">Make admin</button>
        {% endif %}
    </div>
    <div class="xl-ms-product-inventory">
        <h2>Tailler Customers</h2>
        <div id="today_details">
            <table style="width:100%;">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Image</th>
                        <th>Details</th>
                        <th>Total</th>
                        <th>Discount</th>
                        <th>Total Net</th>
                    </tr>
                </thead>
                <tbody style="text-align:center;">
                    {% if customers_detail %}
                        {% for bill in customers_detail %}
                            <tr class="single_bill_tr" id="open_single_bill{{bill.pk}}" href="{% url 'managment_get_single_bill' bill.pk %}" style="cursor:pointer;">
                                <td>{{bill.receipt_number}}</td>
                                <td>
                                    {% if bill.user %}
                                        {% if bill.user.profile_image %}
                                            <img style="width:40px;" src="{{bill.user.profile_image.url}}" />
                                        {% else %}
                                            <img style="width:40px;" src="{% static 'images/default_user.jpg' %}" />
                                        {% endif %}
                                    {% else %}
                                        <img style="width:40px;" src="{% static 'images/default_user.jpg' %}" />
                                    {% endif %}
                                </td>
                                <td>
                                    {% if bill.user %}
                                        <strong>{{bill.user.full_name}}</strong>
                                    {% else %}
                                        <strong>{{bill.username}}</strong>
                                    {% endif %}
                                </td>
                                <td>{{bill.total_paid|intcomma}} {{setting.currency}}</td>
                                <td>{{bill.discount|intcomma}} {{setting.currency}}</td>
                                <td>{{bill.total_net|intcomma}} {{setting.currency}}</td>
                            </tr>
                            <script type="text/javascript">
                                $("#open_single_bill{{bill.pk}}").magnificPopup({type: 'ajax'});
                            </script>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td style="padding:20px 0;" colspan="7"><p class="xl-error">NO BILL FOR THIS TELLER</p></td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(".xl-ms-product-inventory").slimScroll({
        railVisible: true,
        size:'7',
        height:'calc(100vh - 150px)',
        alwaysVisible: false
    });

    $("#open_edit_ms_teller").magnificPopup({type:'ajax'});

    $("#change_teller_is_admin").click(function(e){
        e.preventDefault();
        var url = $(this).attr("data-url");
        var about = $(this).attr("data-about");

        var title = about == "make" ? "Make Admin" : "Unmake Admin";
        var content = about == "make" ? "Do you really want to make this teller admin ???" : "DO you really want to unmake this teller admin ???"

        $.confirm({
            title: title,
            content: content,
            icon: 'icon ion-help-circled',
            animation: 'scale',
            theme:'material',
            type:'blue',
            closeAnimation: 'scale',
            opacity: 0.5,
            buttons:{
                'confirm':{
                    text: 'Yes',
                    btnClass: 'btn-green',
                    action: function(){
                        $.ajax({
                            type:'POST',
                            url:url,
                            data:{},
                            success:function(success){
                                loadMSProductts("{% url 'managment_mstl_single_teller' teller.pk %}");
                                $.alert({theme:'material',title:'Success',icon:'icon ion-checkmark-circled',content:success,type: 'green'});
                            },
                            error: function(error){
                                showErrorMessage("error", error);
                            }
                        });
                    }
                },
                cancel:function(){
                },
            }
        });
    });
</script>

templates/managment/msteller/tellers.html
{% load staticfiles %}
{% load humanize %}
{% if tellers %}
<ul style="border-top:1px solid #DDD">
    {% for teller in tellers %}
         <li><a data-url="{% url 'managment_mstl_single_teller' teller.pk %}" class="load_msp_product"><img src="{{teller.teller_image.url}}" /> <span>{{teller.full_name}}</span><span class="xl-ms-arrow"><i class="icon ion-ios-arrow-right"></i></span></a></li>
    {% endfor %}
</ul>
{% else %}
    <p class="xl-error">NO TELLER</p>
{% endif %}

<button href="{% url 'managment_mstl_add' %}" id="add_new_teller" style="width:100%; margin-top:10px; padding:5px 0; font-size:17px; color:#FFF; text-align:center; background:#00C6D7;">ADD TELLER</button>

<script type="text/javascript">
    $(".load_msp_product").click(function(ev){
        $("#msp_products_loader").show();
        loadMSProductts($(this).attr('data-url'));
        $(this).parent('li').addClass('activated').siblings().removeClass('activated');
    });
    $("#add_new_teller").magnificPopup({type:'ajax'});
</script>